2025-09-18 16:20:00,143 ERROR scheduler Exception in Enqueue Events for Site titans-trivia.local
Traceback (most recent call last):
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/database/database.py", line 839, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/__init__.py", line 1338, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/model/meta.py", line 70, in get_meta
    meta = Meta(doctype)
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/model/meta.py", line 124, in __init__
    super().__init__("DocType", doctype)
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/model/meta.py", line 130, in load_from_db
    super().load_from_db()
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/model/document.py", line 179, in load_from_db
    frappe.throw(
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/__init__.py", line 609, in throw
    msgprint(
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/__init__.py", line 574, in msgprint
    _raise_exception()
  File "/home/tanya/Frappe/Titan-Trivia/titansoft-games/apps/frappe/frappe/__init__.py", line 525, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: DocType System Settings not found
